### PR TITLE
Upgraded packages, and fixed deprecation warnings

### PR DESCRIPTION
**Pull request by Crecket**
I seem to have fixed most of the warnings from outdated/deprecated packages. I updated things like react and material-ui to the latest version which seems to work fine.

### CODE REVIEW

**Comment by hyojin** [comment]
@Crecket Hi, thanks for your PR
I've tested it and I found 2 things we need to check before upgrading the material-ui module. 
first one is that check boxes are not working properly with material-ui 0.18.0 and
second one is that it print a warning in runtime.
```
Warning: Unknown prop `onCellDoubleClick` on <tbody> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```
I'll merge it after I find reasons and fix that. :)

**Comment by hyojin** [comment]
#21

**Comment by Crecket** [comment]
Could you publish these changes to npm? Thanks for fixing that other issue btw

**Comment by hyojin** [comment]
@Crecket Sure, I'll publish within the week! :)

**Comment by hyojin** [comment]
@Crecket Pls try 0.18.0 :)

**Pull request merged**
